//
//  ParseConstants.swift
//  OnTheMapApp
//
//  Created by Andrew Jenson on 11/13/17.
//  Copyright © 2017 Andrew Jenson. All rights reserved.
//

// For "On the Map", you will be required to interact with the Parse API to access data about pin locations and links in the cloud.

import Foundation

extension ParseClient {

    struct Constants {

        // MARK: Parse Base URL

        // For "On the Map", you will be required to interact with the Parse API to access data about pin locations and links in the cloud.

        // Udacity Create An Account
        static let UdacitySignUpURL = "https://www.udacity.com/account/auth#!/signup"

        // To create a new student location, you'll want to use the following API method
        static let ParseUdacityPOST = "https://parse.udacity.com/parse/classes/StudentLocation"

        // To update an existing student location, you'll want to use the following API method
        static let ParseUdacityPUT = "https://parse.udacity.com/parse/classes/StudentLocation/8ZExGR5uX8"

        // static let APIBaseURL = "https://parse.udacity.com/parse/classes"
        static let APIScheme = "https"
        static let APIHost = "parse.udacity.com"
        static let APIPath = "/parse/classes"

        // You will be required to specify the Parse Application ID and REST API Key for all requests to the Parse API.
        // TODO: ??? Does the statment above mean that I should move these down to Parameter Keys and Values?
        static let ApplicationID = "QrX47CA9cyuGewLdsL7o5Eb8iug6Em8ye0dnAbIr"
        static let RestAPIKey = "QuWThTdiRmTux3YaDseUSEpUKo7aBYM737yKd4gY"
        static let ApplicationIDHeader = "X-Parse-Application-Id"
        static let RestAPIKeyHeader = "X-Parse-REST-API-Key"
    }

    // MARK: Methods
    struct Methods {
        static let StudentLocation = "/StudentLocation"
        static let AStudentLocation = "/StudentLocation?where=%7B%22uniqueKey%22%3A%221234%22%7D"
        static let PUTAStudentLocation = "/StudentLocation/{objectId}"
    }

    // MARK: URL Querry Keys
    struct QueryKeys {
        static let limitKey = "limit"
        static let skipKey = "skip"
        static let orderKey = "order"
        static let whereKey = "where"
    }

    // MARK: URL Querry Values
    struct QueryValues {
        static let orderValue = "-updatedAt"
        static let whereValue = "{\"uniqueKey\":\"\(userUniqueKey)\"}"  // whereValue links to accountKey parsed from func authenticateUser() in UdacityConveinence.swift
    }

    // MARK: JSON Response Keys
    struct ResponseKeys {

        // MARK: StudentLocations
        static let StudentLocationResults = "results"
        static let ObjectId = "objectId"
        static let UniqueKey = "uniqueKey"
        static let FirstName = "firstName"
        static let LastName = "lastName"
        static let MapString = "mapString"
        static let MediaURL = "mediaURL"
        static let Latitude = "latitude"
        static let Longitude = "longitude"
        static let CreatedAt = "createdAt"
        static let UpdatedAt = "updatedAt"
        static let ACL = "ACL"

    }


    // Parse, like many other API’s, treats data as objects. These objects are very similar to objects in Swift. For “On the Map”, you will be working with 'StudentLocation' objects.
    // StudentLocation object in Parse, is used by "On the Map" to populate its map view with pins and its other views with information submitted by users.
    // In Parse, each StudentLocation is represented as a collection of key/value pair

    // MARK: Parse Parameter Keys

    //    struct ParameterKeys {
    //
    //        // root JSON
    //        static let Results = "results"
    //
    //        // key = "results" : value = [[String:Any]]
    //
    //        // objectId: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    //        // uniqueKey: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
    //        // firstName: the first name of the student which matches their Udacity profile first name
    //        // lastName: the last name of the student which matches their Udacity profile last name
    //        // mapString: the location string used for geocoding the student location
    //        // mediaURL: the URL provided by the student
    //        // latitude: the latitude of the student location (ranges from -90 to 90)
    //        // longitude: the longitude of the student location (ranges from -180 to 180)
    //        // createdAt: the date when the student location was created
    //        // updatedAt: the date when the student location was last updated
    //        // ACL: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
    //        // When you are parsing StudentLocations, the Parse Types can be casted into equivalent Swift types. Any value with the type "Number" may be casted into a floating-point value in Swift. YOU DO NOT HAVE TO WORRY ABOUT PARSING DATE OR ACL TYPES.
    //
    //        // Main JSON
    //        static let ObjectId = "objectId"
    //        static let UniqueKey = "uniqueKey"
    //        static let FirstName = "firstName"
    //        static let LastName = "lastName"
    //        static let MapString = "mapString"
    //        static let MediaURL = "mediaURL"
    //        static let Latitude = "latitude"
    //        static let Longitude = "longitude"
    //        static let CreatedAt = "createdAt"
    //        static let UpdatedAt = "updatedAt"
    //        static let ACL = "ACL"
    //    }




    struct MapSearch {
        static let SearchBBoxHalfWidth = 1.0
        static let SearchBBoxHalfHeight = 1.0
        static let SearchLatRange = (-90.0, 90.0)
        static let SearchLonRange = (-180.0, 180.0)
    }


}






